// Code generated by goctl. DO NOT EDIT.
// Source: account.proto

package server

import (
	"context"

	"one_for_all/services/account/rpc/internal/logic"
	"one_for_all/services/account/rpc/internal/svc"
	"one_for_all/services/account/rpc/pb/account"
)

type AccountServer struct {
	svcCtx *svc.ServiceContext
	account.UnimplementedAccountServer
}

func NewAccountServer(svcCtx *svc.ServiceContext) *AccountServer {
	return &AccountServer{
		svcCtx: svcCtx,
	}
}

func (s *AccountServer) GetUserByName(ctx context.Context, in *account.GetUserByNameReq) (*account.GetUserByNameRes, error) {
	l := logic.NewGetUserByNameLogic(ctx, s.svcCtx)
	return l.GetUserByName(in)
}
