// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	user "one_for_all/services/account/api/internal/handler/user"
	"one_for_all/services/account/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/user/login",
				Handler: user.LoginHandler(serverCtx),
			},
		},
		rest.WithPrefix("/account/v1"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.UserTokenMiddleware},
			[]rest.Route{
				{
					Method:  http.MethodGet,
					Path:    "/user",
					Handler: user.GetUsersHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/user/:username",
					Handler: user.GetUserHandler(serverCtx),
				},
			}...,
		),
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
		rest.WithPrefix("/account/v1"),
	)
}
